/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Office_Couch_Brown_02: THREE.Mesh
    Office_Table_Coffee_03_Brown: THREE.Mesh
    Office_Misc_Plant_03: THREE.Mesh
    Office_Misc_Coffee_Mug: THREE.Mesh
    Office_Misc_Plant_01: THREE.Mesh
    marble_room_wall: THREE.Mesh
    marble_room_floor: THREE.Mesh
    Office_Misc_Wall_Corkboard_02: THREE.Mesh
    Project_room003: THREE.Mesh
    Project_room003_1: THREE.Mesh
    Project_room003_2: THREE.Mesh
    Project_room003_3: THREE.Mesh
    Project_room003_4: THREE.Mesh
    Project_room003_5: THREE.Mesh
    Project_room_staircase: THREE.Mesh
    Project_room_staircase001: THREE.Mesh
    Project_room_staircase002: THREE.Mesh
    Project_room_staircase003: THREE.Mesh
    Project_room_staircase004: THREE.Mesh
    Project_room_staircase005: THREE.Mesh
    Project_room_staircase006: THREE.Mesh
    Project_room_staircase007: THREE.Mesh
    Project_room_staircase008: THREE.Mesh
    Project_room_staircase009: THREE.Mesh
    Project_MechaTrooper: THREE.Mesh
    Project_FieldFighter: THREE.Mesh
    desktop001: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
    ['palette.001']: THREE.MeshStandardMaterial
    ['palette.002']: THREE.MeshStandardMaterial
    ['palette.003']: THREE.MeshStandardMaterial
    ['palette.005']: THREE.MeshStandardMaterial
    ['palette.009']: THREE.MeshStandardMaterial
    ['palette.010']: THREE.MeshStandardMaterial
    ['palette.012']: THREE.MeshStandardMaterial
    ['palette.041']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['palette.039']: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    RedMetal: THREE.MeshStandardMaterial
    ['palette.043']: THREE.MeshStandardMaterial
    Staircase: THREE.MeshStandardMaterial
    ['Staircase.001']: THREE.MeshStandardMaterial
    ['Staircase.002']: THREE.MeshStandardMaterial
    ['Staircase.003']: THREE.MeshStandardMaterial
    ['Staircase.004']: THREE.MeshStandardMaterial
    ['Staircase.005']: THREE.MeshStandardMaterial
    ['Staircase.006']: THREE.MeshStandardMaterial
    ['Staircase.007']: THREE.MeshStandardMaterial
    ['Staircase.008']: THREE.MeshStandardMaterial
    ['Staircase.009']: THREE.MeshStandardMaterial
    ['palette.013']: THREE.MeshStandardMaterial
    ['palette.042']: THREE.MeshStandardMaterial
    ['palette.044']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/office6.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Couch_Brown_02.geometry}
        material={materials.palette}
        position={[0.5, 0.2, -1.2]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Table_Coffee_03_Brown.geometry}
        material={materials['palette.001']}
        position={[0.5, 0.2, 0.58]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Misc_Plant_03.geometry}
        material={materials['palette.002']}
        position={[-1.5, 0.2, -1.25]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Misc_Coffee_Mug.geometry}
        material={materials['palette.003']}
        position={[-0.51, 0.7, 0.22]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Misc_Plant_01.geometry}
        material={materials['palette.005']}
        position={[1.45, 0.7, 0.69]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.marble_room_wall.geometry}
        material={materials['palette.009']}
        position={[-2, -2, -2]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.marble_room_floor.geometry}
        material={materials['palette.010']}
        position={[-2, -2, -2]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_Misc_Wall_Corkboard_02.geometry}
        material={materials['palette.012']}
        position={[1.04, 1.93, -1.1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[2, -3, 3]} rotation={[Math.PI / 2, 0, 0]} scale={[0.99, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Project_room003.geometry} material={materials['palette.041']} />
        <mesh castShadow receiveShadow geometry={nodes.Project_room003_1.geometry} material={materials.Glass} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Project_room003_2.geometry}
          material={materials['palette.039']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Project_room003_3.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Project_room003_4.geometry} material={materials.RedMetal} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Project_room003_5.geometry}
          material={materials['palette.043']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase.geometry}
        material={materials.Staircase}
        position={[4, 0, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase001.geometry}
        material={materials['Staircase.001']}
        position={[5.8, 1.8, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase002.geometry}
        material={materials['Staircase.002']}
        position={[4.2, 0.2, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase003.geometry}
        material={materials['Staircase.003']}
        position={[4.4, 0.4, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase004.geometry}
        material={materials['Staircase.004']}
        position={[4.6, 0.6, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase005.geometry}
        material={materials['Staircase.005']}
        position={[4.8, 0.8, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase006.geometry}
        material={materials['Staircase.006']}
        position={[5, 1, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase007.geometry}
        material={materials['Staircase.007']}
        position={[5.2, 1.2, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase008.geometry}
        material={materials['Staircase.008']}
        position={[5.4, 1.4, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_room_staircase009.geometry}
        material={materials['Staircase.009']}
        position={[5.6, 1.6, 1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_MechaTrooper.geometry}
        material={materials['palette.013']}
        position={[5.64, 4.8, 2.22]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Project_FieldFighter.geometry}
        material={materials['palette.042']}
        position={[3.23, 4.89, -1.68]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desktop001.geometry}
        material={materials['palette.044']}
        position={[2.92, 0.4, 1.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.9}
      />
    </group>
  )
}

useGLTF.preload('/office6.glb')
